export { default as AddCart } from './AddToCart/AddToCart'
export { default as BookMarkButton } from './BookMarkButton/BookMarkButton'
export { default as FavoritesButton } from './FavoritesButton/FavoritesButton'
export { default as Reviews } from './Reviews/Reviews'
export { default as Slider } from './Slider/Slider'
