export { default as commentsAdmin } from './blog/comments'
export { default as postsAdmin } from './blog/posts'
export { default as orderAdmin } from './shop/order'
export { default as productsAdmin } from './shop/products'
export { default as reviewsAdmin } from './shop/review'
